############################
# TLS TO BROKER
############################
security.protocol=SASL_SSL
ssl.truststore.type=PKCS12
ssl.truststore.location=/etc/kafka/secrets/truststore.p12
ssl.truststore.password=120103
sasl.mechanism=OAUTHBEARER

############################
# STRIMZI LOGIN HANDLER
############################
sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler

############################
# OAUTH JAAS CONFIG
############################
sasl.jaas.config=\
org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
    oauth.token.endpoint.uri="http://keycloak:8080/realms/kafka/protocol/openid-connect/token" \
    oauth.client.id="backend" \
    oauth.assertion.private.key.file="/etc/kafka/secrets/oauth/private.key" \
    oauth.assertion.private.key.passphrase="120103" \
    oauth.assertion.algorithm="RS256" \
    oauth.scope="kafka.produce kafka.consume" \
    oauth.groups="groups" \
    oauth.audience="account" \
    oauth.ssl.truststore.type="PKCS12" \
    oauth.ssl.truststore.location="/etc/kafka/secrets/truststore.p12" \
    oauth.ssl.truststore.password="120103";
