#!/bin/bash

create_client_files() {
  echo "Creating client files"
  rm -rf kafka/configs/*

  envsubst < templates/server.template > kafka/configs/server.properties
  envsubst < templates/client.template > kafka/configs/client.properties
}

create_env_file() {
    # Clean old content before overwrite
    : > .env
    mkdir -p secrets/kafka1
    mkdir -p secrets/postgresql
    : > secrets/kafka1/kafka.secret
    : > secrets/postgresql/postgresql.password

    echo "$CERT_SECRET" >> secrets/kafka1/kafka.secret
    echo "$POSTGRES_PASSWORD" >> secrets/postgresql/postgresql.password

    {
      echo POSTGRES_USER="$POSTGRES_USER"
      echo POSTGRES_PASSWORD="$POSTGRES_PASSWORD"

      echo MONGODB_USERNAME="$MONGODB_USERNAME"
      echo MONGODB_PASSWORD="$MONGODB_PASSWORD"

      echo KC_BOOTSTRAP_ADMIN_USERNAME="$KC_BOOTSTRAP_ADMIN_USERNAME"
      echo KC_BOOTSTRAP_ADMIN_PASSWORD="$KC_BOOTSTRAP_ADMIN_PASSWORD"

      echo CERT_SECRET="$CERT_SECRET"

      echo BROKER_HEAP="$BROKER_HEAP"
      echo SCHEMA_HEAP="$SCHEMA_HEAP"
      echo SSL_CIPHER_SUITES="$SSL_CIPHER_SUITES"
      echo KAFKA_OAUTH_LIB_VERSION="$KAFKA_OAUTH_LIB_VERSION"
      echo NIMBUS_JWT_LIB_VERSION="$NIMBUS_JWT_LIB_VERSION"
      echo PROMETHEUS_JAVAAGENT_VERSION="$PROMETHEUS_JAVAAGENT_VERSION"

      echo KAFKA_IDP_TOKEN_ENDPOINT="$KAFKA_IDP_TOKEN_ENDPOINT"
      echo KAFKA_IDP_JWKS_ENDPOINT="$KAFKA_IDP_JWKS_ENDPOINT"
      echo KAFKA_IDP_EXPECTED_ISSUER="$KAFKA_IDP_EXPECTED_ISSUER"
      echo KAFKA_IDP_AUTH_ENDPOINT="$KAFKA_IDP_AUTH_ENDPOINT"
      echo KAFKA_IDP_DEVICE_AUTH_ENDPOINT="$KAFKA_IDP_DEVICE_AUTH_ENDPOINT"
      echo KAFKA_SUB_CLAIM_NAME="$KAFKA_SUB_CLAIM_NAME"
      echo KAFKA_SCOPE_CLAIM_NAME="$KAFKA_SCOPE_CLAIM_NAME"
      echo KAFKA_GROUP_CLAIM_NAME="$KAFKA_GROUP_CLAIM_NAME"
      echo KAFKA_EXPECTED_AUDIENCE="$KAFKA_EXPECTED_AUDIENCE"

      # Client configurations
      echo KAFKA_SUPERUSER_CLIENT_ID="$KAFKA_SUPERUSER_CLIENT_ID"
      echo KAFKA_SUPERUSER_CLIENT_SECRET="$KAFKA_SUPERUSER_CLIENT_SECRET"

      echo KAFKA_SR_CLIENT_ID="$KAFKA_SR_CLIENT_ID"
      echo KAFKA_SR_CLIENT_SECRET="$KAFKA_SR_CLIENT_SECRET"

      echo KAFKA_C3_CLIENT_ID="$KAFKA_C3_CLIENT_ID"
      echo KAFKA_C3_CLIENT_SECRET="$KAFKA_C3_CLIENT_SECRET"

      echo KAFKA_CLIENT_ID="$KAFKA_CLIENT_ID"
      echo KAFKA_CLIENT_SECRET="$KAFKA_CLIENT_SECRET"

      echo KAFKA_SSO_CLIENT_ID="$KAFKA_SSO_CLIENT_ID"
      echo KAFKA_SSO_CLIENT_SECRET="$KAFKA_SSO_CLIENT_SECRET"

      echo KAFKA_SSO_SUPER_USER_GROUP="$KAFKA_SSO_SUPER_USER_GROUP"
      echo KAFKA_SSO_USER_GROUP="$KAFKA_SSO_USER_GROUP"

      echo AUTH_CLIENT_ID="$AUTH_CLIENT_ID"
      echo AUTH_CLIENT_SECRET="$AUTH_CLIENT_SECRET"

      echo CONCERT_CLIENT_ID="$CONCERT_CLIENT_ID"
      echo CONCERT_CLIENT_SECRET="$CONCERT_CLIENT_SECRET"

      echo BOOKING_CLIENT_ID="$BOOKING_CLIENT_ID"
      echo BOOKING_CLIENT_SECRET="$BOOKING_CLIENT_SECRET"

    } >> .env

}

